### ISSUE TITLE
upgrade dependency versions

### ISSUE THREAD

**Issue by jurko-gospodnetic** [chesleybrown/grunt-tabs4life#4]
Some dependency versions that could be upgraded:
- `lodash 3.8.0`
- `grunt-jscs 1.8.0`
- `grunt-lintspaces 0.6.2`
- `grunt-contrib-jshint 0.11.2`

**Comment by chesleybrown** [comment]
These are all the same major version which is what the `caret` symbol installs.

> In the simplest terms, the tilde matches the most recent minor version (the middle number). ~1.2.3 will match all 1.2.x versions but will miss 1.3.0.
> 
> The caret, on the other hand, is more relaxed. It will update you to the most recent major version (the first number). ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.
